apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: wild-west-frontend
  namespace: pdave
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: purple-mermaid-app
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: wild-west-frontend
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: wild-west-frontend-
      labels:
        build.appstudio.openshift.io/application: purple-mermaid-app
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: wild-west-frontend
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: pdave
    spec:
      params:
      - name: git-url
        value: https://github.com/openshift-evangelists/Wild-West-Frontend
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:pdave-wild-west-frontend-$(tt.params.git-revision)
      - name: dockerfile
        value: Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:7170560e64e33af5fc37ba01531cbefdd2dc4fce
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: wild-west-frontend/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
